apiVersion: batch/v1
kind: Job
metadata:
  name: benchmarking-1-2
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: client1
        image: ravitella/bootstrapper:latest
        imagePullPolicy: Always
        command: ["./execute-kubernetes.sh"]
        resources:
           limits:
             memory: "4G"
             cpu: "6000m"
        env:
        - name: ADMIN_USER_NAME
          value: "benchmarking"
        - name: POD_NAME
          value: "client1"
        - name: POD_INDEX
          value: "1"  
        - name: POD_COUNT
          value: "2"  
        - name: WRITE_ONLY_OPERATION
          value: "true"
        - name: RESULT_STORAGE_CONNECTION_STRING
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: RESULT_STORAGE_CONNECTION_STRING
        - name: COSMOS_URI
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_URI
        - name: COSMOS_KEY
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_KEY  
        - name: GUID
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: GUID   
        - name: TARGET_OPERATIONS_PER_SECOND
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: TARGET_OPERATIONS_PER_SECOND
        - name: THREAD_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: THREAD_COUNT
        - name: YCSB_OPERATION_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_OPERATION_COUNT
        - name: WORKLOAD_TYPE
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: WORKLOAD_TYPE
        - name: USE_GATEWAY
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: USE_GATEWAY
        - name: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS        
        - name: REQUEST_DISTRIBUTION
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: REQUEST_DISTRIBUTION
        - name: INSERT_ORDER
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: INSERT_ORDER
        - name: INCLUDE_EXCEPTION_STACK
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: INCLUDE_EXCEPTION_STACK
        - name: FIELD_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: FIELD_COUNT
        - name: BENCHMARKING_FRAMEWORK_REPO
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: BENCHMARKING_FRAMEWORK_REPO
        - name: BENCHMARKING_FRAMEWORK_BRANCH
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: BENCHMARKING_FRAMEWORK_BRANCH
        - name: YCSB_REPO
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_REPO
        - name: YCSB_BRANCH
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_BRANCH
        - name: DB_BINDING_NAME
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: DB_BINDING_NAME
      restartPolicy: Never
  backoffLimit: 0
  
---
  
apiVersion: batch/v1
kind: Job
metadata:
  name: benchmarking-2-2
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: client2
        image: ravitella/bootstrapper:latest
        imagePullPolicy: Always
        command: ["./execute-kubernetes.sh"]
        resources:
           limits:
             memory: "4G"
             cpu: "6000m"
        env:
        - name: ADMIN_USER_NAME
          value: "benchmarking"
        - name: POD_NAME
          value: "client2"
        - name: POD_INDEX
          value: "2"  
        - name: POD_COUNT
          value: "2"  
        - name: WRITE_ONLY_OPERATION
          value: "true"
        - name: RESULT_STORAGE_CONNECTION_STRING
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: RESULT_STORAGE_CONNECTION_STRING
        - name: COSMOS_URI
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_URI
        - name: COSMOS_KEY
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_KEY  
        - name: GUID
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: GUID   
        - name: TARGET_OPERATIONS_PER_SECOND
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: TARGET_OPERATIONS_PER_SECOND
        - name: THREAD_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: THREAD_COUNT
        - name: YCSB_OPERATION_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_OPERATION_COUNT
        - name: WORKLOAD_TYPE
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: WORKLOAD_TYPE
        - name: USE_GATEWAY
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: USE_GATEWAY
        - name: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS        
        - name: REQUEST_DISTRIBUTION
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: REQUEST_DISTRIBUTION
        - name: INSERT_ORDER
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: INSERT_ORDER
        - name: INCLUDE_EXCEPTION_STACK
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: INCLUDE_EXCEPTION_STACK
        - name: FIELD_COUNT
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: FIELD_COUNT
        - name: BENCHMARKING_FRAMEWORK_REPO
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: BENCHMARKING_FRAMEWORK_REPO
        - name: BENCHMARKING_FRAMEWORK_BRANCH
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: BENCHMARKING_FRAMEWORK_BRANCH
        - name: YCSB_REPO
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_REPO
        - name: YCSB_BRANCH
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: YCSB_BRANCH
        - name: DB_BINDING_NAME
          valueFrom:
             configMapKeyRef:
               name: benchmarking-recipe-config
               key: DB_BINDING_NAME
      restartPolicy: Never
  backoffLimit: 0