apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrapperjob
spec:
  template:
    spec:
      containers:
      - name: bootstrapper1
        image: ravitella/bootstrapper:latest
        command: ["./custom-script.sh"]
        env:
        - name: ADMIN_USER_NAME
          value: "benchmarking"
        - name: VM_NAM
          value: "bootstrapper1"
        - name: MACHINE_INDEX
          value: "1"  
        - name: VM_COUNT
          value: "1"  
        - name: RESULT_STORAGE_CONNECTION_STRING
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: RESULT_STORAGE_CONNECTION_STRING
        - name: COSMOS_URI
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: COSMOS_URI
        - name: COSMOS_KEY
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: COSMOS_KEY
        - name: GUID
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: GUID       
        - name: TARGET_OPERATIONS_PER_SECOND
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: TARGET_OPERATIONS_PER_SECOND
        - name: THREAD_COUNT
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: THREAD_COUNT
        - name: YCSB_OPERATION_COUNT
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: YCSB_OPERATION_COUNT
        - name: WORKLOAD_TYPE
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: WORKLOAD_TYPE
        - name: YCSB_RECORD_COUNT
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: YCSB_RECORD_COUNT
        - name: USE_GATEWAY
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: USE_GATEWAY
        - name: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS        
        - name: REQUEST_DISTRIBUTION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: REQUEST_DISTRIBUTION
        - name: INSERT_ORDER
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: INSERT_ORDER
        - name: INCLUDE_EXCEPTION_STACK
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: INCLUDE_EXCEPTION_STACK
        - name: FIELD_COUNT
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: FIELD_COUNT
        - name: SKIP_LOAD_PHASE
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: SKIP_LOAD_PHASE
        - name: WRITE_ONLY_OPERATION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: WRITE_ONLY_OPERATION    
        - name: READ_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: READ_PROPORTION
        - name: SCAN_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: SCAN_PROPORTION
        - name: UPDATE_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: UPDATE_PROPORTION
        - name: INSERT_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: INSERT_PROPORTION
        - name: BENCHMARKING_TOOLS_URL
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: BENCHMARKING_TOOLS_URL
        - name: BENCHMARKING_TOOLS_BRANCH_NAME
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: BENCHMARKING_TOOLS_BRANCH_NAME
        - name: BENCHMARKING_TOOLS_BRANCH_NAME
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: BENCHMARKING_TOOLS_BRANCH_NAME      
        - name: YCSB_GIT_REPO_URL
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: YCSB_GIT_REPO_URL
        - name: CUSTOM_SCRIPT_URL
          valueFrom:
             configMapKeyRef:
               name: common-env-config
               key: CUSTOM_SCRIPT_URL                      
      restartPolicy: Never
  backoffLimit: 0

