apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrapperjob-simple
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: client1
        image: ravitella/bootstrapper:latest
        imagePullPolicy: Always
        command: ["./execute-kubernetes.sh"]
        resources:
           limits:
             memory: "4G"
             cpu: "6000m"
        env:
        - name: ADMIN_USER_NAME
          value: "benchmarking"
        - name: VM_NAME
          value: "client1"
        - name: MACHINE_INDEX
          value: "1"  
        - name: VM_COUNT
          value: "1"  
        - name: RESULT_STORAGE_CONNECTION_STRING
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: RESULT_STORAGE_CONNECTION_STRING
        - name: COSMOS_URI
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_URI
        - name: COSMOS_KEY
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: COSMOS_KEY  
        - name: GUID
          valueFrom:
             secretKeyRef:
               name: benchmarking-secrets
               key: GUID   
        - name: TARGET_OPERATIONS_PER_SECOND
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: TARGET_OPERATIONS_PER_SECOND
        - name: THREAD_COUNT
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: THREAD_COUNT
        - name: YCSB_OPERATION_COUNT
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: YCSB_OPERATION_COUNT
        - name: WORKLOAD_TYPE
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: WORKLOAD_TYPE
        - name: YCSB_RECORD_COUNT
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: YCSB_RECORD_COUNT
        - name: USE_GATEWAY
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: USE_GATEWAY
        - name: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: DIAGNOSTICS_LATENCY_THRESHOLD_IN_MS        
        - name: REQUEST_DISTRIBUTION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: REQUEST_DISTRIBUTION
        - name: INSERT_ORDER
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: INSERT_ORDER
        - name: INCLUDE_EXCEPTION_STACK
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: INCLUDE_EXCEPTION_STACK
        - name: FIELD_COUNT
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: FIELD_COUNT
        - name: SKIP_LOAD_PHASE
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: SKIP_LOAD_PHASE
        - name: WRITE_ONLY_OPERATION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: WRITE_ONLY_OPERATION    
        - name: READ_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: READ_PROPORTION
        - name: SCAN_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: SCAN_PROPORTION
        - name: UPDATE_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: UPDATE_PROPORTION
        - name: INSERT_PROPORTION
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: INSERT_PROPORTION
        - name: BENCHMARKING_FRAMEWORK_REPO
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: BENCHMARKING_FRAMEWORK_REPO
        - name: BENCHMARKING_FRAMEWORK_BRANCH
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: BENCHMARKING_FRAMEWORK_BRANCH
        - name: YCSB_REPO
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: YCSB_REPO
        - name: YCSB_BRANCH
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: YCSB_BRANCH
        - name: DB_BINDING_NAME
          valueFrom:
             configMapKeyRef:
               name: test-env-config
               key: DB_BINDING_NAME
      restartPolicy: Never
  backoffLimit: 0